## Module: balance.gd
## Restored English comments for maintainability and i18n coding standards.

class_name Balance
extends RefCounted

const STARTING_MONEY := 500

const TICKET_BASE_PRICE := 2

const TICKET_MULTIPLIER_SHORT := 1.0
const TICKET_MULTIPLIER_MEDIUM := 1.5
const TICKET_MULTIPLIER_LONG := 2.0

const FARE_MULTIPLIER_NORMAL := 1.0
const FARE_MULTIPLIER_VIP := 3.0
const FARE_MULTIPLIER_STUDENT := 0.5
const FARE_MULTIPLIER_ELDERLY := 0.7

const REPUTATION_MIN := 0.0
const REPUTATION_MAX := 5.0

const REPUTATION_STARTING := 3.0

const REPUTATION_LOSS_MULTIPLIER := 0.5

const REPUTATION_PER_PASSENGER_DELIVERED := 0.1
const REPUTATION_PER_PASSENGER_LOST := -0.2

const PATIENCE_BASE := 30.0

const PATIENCE_MULTIPLIER_NORMAL := 1.0
const PATIENCE_MULTIPLIER_VIP := 0.5
const PATIENCE_MULTIPLIER_STUDENT := 1.5
const PATIENCE_MULTIPLIER_ELDERLY := 1.0

const FUEL_CONSUMPTION_COAL_OLD := 3.0
const FUEL_CONSUMPTION_COAL_NEW := 2.5
const FUEL_CONSUMPTION_DIESEL_OLD := 2.0
const FUEL_CONSUMPTION_DIESEL_NEW := 1.5
const FUEL_CONSUMPTION_ELECTRIC := 1.0

const FUEL_TANK_COAL_OLD := 300.0
const FUEL_TANK_COAL_NEW := 400.0
const FUEL_TANK_DIESEL_OLD := 500.0
const FUEL_TANK_DIESEL_NEW := 600.0
const FUEL_TANK_ELECTRIC := 800.0

const FUEL_LOW_THRESHOLD := 25.0
const FUEL_CRITICAL_THRESHOLD := 10.0

const FUEL_UNIT_PRICE := 1.0

const FUEL_PER_WAGON_MULTIPLIER := 0.1

const LOCOMOTIVE_SPEED_COAL_OLD := 60.0
const LOCOMOTIVE_SPEED_COAL_NEW := 75.0
const LOCOMOTIVE_SPEED_DIESEL_OLD := 80.0
const LOCOMOTIVE_SPEED_DIESEL_NEW := 100.0
const LOCOMOTIVE_SPEED_ELECTRIC := 120.0

const LOCOMOTIVE_COST_COAL_OLD := 200
const LOCOMOTIVE_COST_COAL_NEW := 500
const LOCOMOTIVE_COST_DIESEL_OLD := 1000
const LOCOMOTIVE_COST_DIESEL_NEW := 2000
const LOCOMOTIVE_COST_ELECTRIC := 5000

const WAGON_COST_ECONOMY := 100
const WAGON_COST_BUSINESS := 200
const WAGON_COST_VIP := 300
const WAGON_COST_DINING := 250
const WAGON_COST_CARGO := 80

const WAGON_WEIGHT := 15.0

const PASSENGER_ALIGHT_DURATION := 1.5

const PASSENGER_BOARD_DURATION := 1.0

const RANDOM_EVENT_MAX_PER_TRIP := 2
const RANDOM_EVENT_MOTOR_PROBABILITY := 0.12
const RANDOM_EVENT_DOOR_PROBABILITY := 0.10
const RANDOM_EVENT_VIP_PROBABILITY := 0.15
const RANDOM_EVENT_SICK_PROBABILITY := 0.08
const RANDOM_EVENT_FUEL_HIKE_PROBABILITY := 0.10
const RANDOM_EVENT_FESTIVAL_PROBABILITY := 0.12

const EVENT_SPEED_MULTIPLIER_MOTOR := 0.5
const EVENT_STATION_TIME_DELTA_DOOR := -5.0
const EVENT_PASSENGER_MULTIPLIER_FESTIVAL := 2.0
const EVENT_VIP_EXTRA_COUNT := 1
const EVENT_REPUTATION_SICK_BONUS := 0.5
const EVENT_FUEL_PRICE_MULTIPLIER_HIKE := 1.5

const QUEST_REWARD_EGE_01_MONEY := 100
const QUEST_REWARD_EGE_02_MONEY := 150
const QUEST_REWARD_EGE_03_MONEY := 200
const QUEST_REWARD_EGE_04_MONEY := 250
const QUEST_REWARD_EGE_05_MONEY := 500

const QUEST_REWARD_EGE_01_REPUTATION := 0.2
const QUEST_REWARD_EGE_02_REPUTATION := 0.3
const QUEST_REWARD_EGE_03_REPUTATION := 0.3
const QUEST_REWARD_EGE_04_REPUTATION := 0.5
const QUEST_REWARD_EGE_05_REPUTATION := 1.0

const QUEST_TARGET_EGE_02_PASSENGERS := 10
const QUEST_TARGET_EGE_04_PASSENGERS := 20

const CARGO_OFFERS_MIN_PER_STATION := 0
const CARGO_OFFERS_MAX_PER_STATION := 2

const SHOP_SLOT_SMALL_STATION := 1
const SHOP_SLOT_BIG_STATION := 2
const SHOP_MAX_LEVEL := 3
const SHOP_BIG_STATION_IDS := ["IZMIR BASMANE", "AYDIN", "DENIZLI"]

const SHOP_COST_L1 := 150
const SHOP_COST_L2 := 300
const SHOP_COST_L3 := 500

const SHOP_REPUTATION_L1 := 1.0
const SHOP_REPUTATION_L2 := 2.0
const SHOP_REPUTATION_L3 := 3.0

const SHOP_BUFFET_INCOME_L1 := 10
const SHOP_BUFFET_INCOME_L2 := 20
const SHOP_BUFFET_INCOME_L3 := 35
const SHOP_SOUVENIR_INCOME_L1 := 8
const SHOP_SOUVENIR_INCOME_L2 := 18
const SHOP_SOUVENIR_INCOME_L3 := 30
const SHOP_BUFFET_PATIENCE_REDUCTION_PER_LEVEL := 0.10

const UPGRADE_MAX_LEVEL := 3
const UPGRADE_REPUTATION_L1 := 1.0
const UPGRADE_REPUTATION_L2 := 2.0
const UPGRADE_REPUTATION_L3 := 3.0
const UPGRADE_RESPEC_REFUND_RATIO := 0.5
const UPGRADE_LINE_LOCK_MIN_LEVEL := 2
const UPGRADE_LINE_LOCK_REQUIRED := "ege_main"

const UPGRADE_LOCO_SPEED_COST_L1 := 100
const UPGRADE_LOCO_SPEED_COST_L2 := 200
const UPGRADE_LOCO_SPEED_COST_L3 := 400
const UPGRADE_LOCO_CAPACITY_COST_L1 := 150
const UPGRADE_LOCO_CAPACITY_COST_L2 := 300
const UPGRADE_LOCO_CAPACITY_COST_L3 := 500
const UPGRADE_LOCO_FUEL_COST_L1 := 120
const UPGRADE_LOCO_FUEL_COST_L2 := 250
const UPGRADE_LOCO_FUEL_COST_L3 := 450
const UPGRADE_LOCO_DURABILITY_COST_L1 := 80
const UPGRADE_LOCO_DURABILITY_COST_L2 := 180
const UPGRADE_LOCO_DURABILITY_COST_L3 := 350

const UPGRADE_SPEED_MULTIPLIER_PER_LEVEL := 0.90
const UPGRADE_FUEL_MULTIPLIER_PER_LEVEL := 0.85
const UPGRADE_DURABILITY_MULTIPLIER_PER_LEVEL := 0.75

const UPGRADE_WAGON_COMFORT_COST_L1 := 60
const UPGRADE_WAGON_COMFORT_COST_L2 := 120
const UPGRADE_WAGON_COMFORT_COST_L3 := 250
const UPGRADE_WAGON_CAPACITY_COST_L1 := 80
const UPGRADE_WAGON_CAPACITY_COST_L2 := 160
const UPGRADE_WAGON_CAPACITY_COST_L3 := 300
const UPGRADE_WAGON_MAINTENANCE_COST_L1 := 50
const UPGRADE_WAGON_MAINTENANCE_COST_L2 := 100
const UPGRADE_WAGON_MAINTENANCE_COST_L3 := 200

const UPGRADE_WAGON_COMFORT_REPUTATION_PER_LEVEL := 0.1
const UPGRADE_WAGON_CAPACITY_PASSENGER_PER_LEVEL := 3
const UPGRADE_WAGON_CAPACITY_CARGO_PER_LEVEL := 2
const UPGRADE_WAGON_MAINTENANCE_MULTIPLIER_PER_LEVEL := 0.8

const LOCOMOTIVE_COST_DEMIR_YUREK := 400
const LOCOMOTIVE_COST_BOZ_KAPLAN := 800
const LOCOMOTIVE_REPUTATION_DEMIR_YUREK := 2.0
const LOCOMOTIVE_REPUTATION_BOZ_KAPLAN := 3.0

const WAGON_COST_VIP_PHASE8 := 300
const WAGON_COST_DINING_PHASE8 := 250
const WAGON_REPUTATION_VIP := 2.5
const WAGON_REPUTATION_DINING := 2.0

const DINING_INCOME_PER_STATION := 5
const DINING_PATIENCE_REDUCTION := 0.05

const ACH_REWARD_TRIP_FIRST := 50
const ACH_REWARD_TRIP_10 := 150
const ACH_REWARD_TRIP_100KM := 100
const ACH_REWARD_TRIP_500KM := 300
const ACH_REWARD_PAX_100 := 100
const ACH_REWARD_PAX_VIP_FIRST := 75
const ACH_REWARD_PAX_ZERO_LOSS := 200
const ACH_REWARD_PAX_500 := 500
const ACH_REWARD_COL_UPGRADE := 50
const ACH_REWARD_COL_LOCO2 := 100
const ACH_REWARD_COL_ALL_WAGONS := 250
const ACH_REWARD_COL_SHOP := 75
const ACH_REWARD_DISC_ALL_EGE := 200
const ACH_REWARD_DISC_CARGO_FIRST := 50
const ACH_REWARD_DISC_EVENT := 30
const ACH_REWARD_DISC_QUEST_ALL := 500

const ACH_TARGET_TRIPS_FIRST := 1
const ACH_TARGET_TRIPS_10 := 10
const ACH_TARGET_KM_100 := 100
const ACH_TARGET_KM_500 := 500
const ACH_TARGET_PAX_100 := 100
const ACH_TARGET_PAX_500 := 500
const ACH_TARGET_PERFECT_MIN_PASSENGERS := 10
const ACH_TARGET_ALL_EGE_STOPS := 7
const ACH_TARGET_ALL_QUESTS := 5

const DIFFICULTY_PERF_LOW := 40.0
const DIFFICULTY_PERF_HIGH := 80.0
const DIFFICULTY_HISTORY_SIZE := 3
const DIFFICULTY_CLAMP_MIN := 0.7
const DIFFICULTY_CLAMP_MAX := 1.5
const DIFFICULTY_TIME_LOW := 1.3
const DIFFICULTY_TIME_MID := 1.0
const DIFFICULTY_TIME_HIGH := 0.85
const DIFFICULTY_PATIENCE_LOW := 1.3
const DIFFICULTY_PATIENCE_MID := 1.0
const DIFFICULTY_PATIENCE_HIGH := 0.85
const DIFFICULTY_BREAKDOWN_LOW := 0.5
const DIFFICULTY_BREAKDOWN_MID := 1.0
const DIFFICULTY_BREAKDOWN_HIGH := 1.3
const DIFFICULTY_INCOME_LOW := 1.15
const DIFFICULTY_INCOME_MID := 1.0
const DIFFICULTY_INCOME_HIGH := 0.95

const ACCESSIBILITY_FONT_SMALL := "small"
const ACCESSIBILITY_FONT_MEDIUM := "medium"
const ACCESSIBILITY_FONT_LARGE := "large"
const ACCESSIBILITY_FONT_MULTIPLIER_SMALL := 1.0
const ACCESSIBILITY_FONT_MULTIPLIER_MEDIUM := 1.25
const ACCESSIBILITY_FONT_MULTIPLIER_LARGE := 1.5
const ACCESSIBILITY_SLOW_MODE_MULTIPLIER := 2.0
