## Module: balance.gd
## Restored English comments for maintainability and i18n coding standards.

class_name Balance
extends RefCounted

const STARTING_MONEY := 500

const TICKET_BASE_PRICE := 2

const TICKET_MULTIPLIER_SHORT := 1.0
const TICKET_MULTIPLIER_MEDIUM := 1.5
const TICKET_MULTIPLIER_LONG := 2.0

const FARE_MULTIPLIER_NORMAL := 1.0
const FARE_MULTIPLIER_VIP := 3.0
const FARE_MULTIPLIER_STUDENT := 0.5
const FARE_MULTIPLIER_ELDERLY := 0.7

const REPUTATION_MIN := 0.0
const REPUTATION_MAX := 5.0

const REPUTATION_STARTING := 3.0

const REPUTATION_LOSS_MULTIPLIER := 0.5

const REPUTATION_PER_PASSENGER_DELIVERED := 0.1
const REPUTATION_PER_PASSENGER_LOST := -0.2

const PATIENCE_BASE := 30.0

const PATIENCE_MULTIPLIER_NORMAL := 1.0
const PATIENCE_MULTIPLIER_VIP := 0.5
const PATIENCE_MULTIPLIER_STUDENT := 1.5
const PATIENCE_MULTIPLIER_ELDERLY := 1.0

const FUEL_CONSUMPTION_COAL_OLD := 3.0
const FUEL_CONSUMPTION_COAL_NEW := 2.5
const FUEL_CONSUMPTION_DIESEL_OLD := 2.0
const FUEL_CONSUMPTION_DIESEL_NEW := 1.5
const FUEL_CONSUMPTION_ELECTRIC := 1.0

const FUEL_TANK_COAL_OLD := 300.0
const FUEL_TANK_COAL_NEW := 400.0
const FUEL_TANK_DIESEL_OLD := 500.0
const FUEL_TANK_DIESEL_NEW := 600.0
const FUEL_TANK_ELECTRIC := 800.0

const FUEL_LOW_THRESHOLD := 25.0
const FUEL_CRITICAL_THRESHOLD := 10.0

const FUEL_UNIT_PRICE := 1.0

const FUEL_PER_WAGON_MULTIPLIER := 0.1

const LOCOMOTIVE_SPEED_COAL_OLD := 60.0
const LOCOMOTIVE_SPEED_COAL_NEW := 75.0
const LOCOMOTIVE_SPEED_DIESEL_OLD := 80.0
const LOCOMOTIVE_SPEED_DIESEL_NEW := 100.0
const LOCOMOTIVE_SPEED_ELECTRIC := 120.0

const LOCOMOTIVE_COST_COAL_OLD := 200
const LOCOMOTIVE_COST_COAL_NEW := 500
const LOCOMOTIVE_COST_DIESEL_OLD := 1000
const LOCOMOTIVE_COST_DIESEL_NEW := 2000
const LOCOMOTIVE_COST_ELECTRIC := 5000

const WAGON_COST_ECONOMY := 100
const WAGON_COST_BUSINESS := 200
const WAGON_COST_VIP := 350
const WAGON_COST_DINING := 150
const WAGON_COST_CARGO := 80

const WAGON_WEIGHT := 15.0

const PASSENGER_ALIGHT_DURATION := 1.5

const PASSENGER_BOARD_DURATION := 1.0
